Created & Updated Carousel components and Footer
kalviumcommunity/PromptVerse pull request #6
Opened 2023-05-14 01:35 UTC by leovaldez08

Created the carousel components like Midjourney.jsx, ChatGpt.jsx and StableDiffusion.jsx. Created CardData files for the carousels. Created Footer section of the page. Also made minor changes in Navbar. Finished the home page.

2023-05-15 07:48 UTC, jithin-kalvian requested changes
Please complete the changes

2023-05-15 07:48 UTC, jithin-kalvian commented on FrontEnd/src/App.jsx
You can use self-closing tags for components without children. This can make your code cleaner. For example, <NavBar></NavBar> can be written as <NavBar/>.

2023-05-15 07:48 UTC, jithin-kalvian commented on FrontEnd/src/Components/Carousel.jsx
In the map function, you're using the index as the key for each Card component. This is generally not recommended in React, because it can cause issues if the order of the items changes. If the cardData has unique identifiers, use those instead.

2023-05-15 10:53 UTC, yash0212 requested changes
Please resolve the comments below

2023-05-15 10:53 UTC, yash0212 commented on FrontEnd/src/Components/Carousel.jsx
> +/* eslint-disable react/prop-types */
Please explain the use of this comment

2023-05-15 10:53 UTC, yash0212 commented on FrontEnd/src/Components/ChatGpt.jsx
> +        <Carousel cardData={cardData}></Carousel>
Since this component doesn't accept any children, this can be a converted to a self closing tag

2023-05-15 10:53 UTC, yash0212 commented on FrontEnd/src/Components/Footer.jsx
> +/* eslint-disable react/prop-types */
Please explain the use of these 2 commented lines

2023-05-15 13:59 UTC, leovaldez08 commented on FrontEnd/src/App.jsx
Noted! Made changes

2023-05-15 13:59 UTC, leovaldez08 commented on FrontEnd/src/Components/ChatGpt.jsx
> +        <Carousel cardData={cardData}></Carousel>
Got it! Made changes!

2023-05-15 14:02 UTC, leovaldez08 commented on FrontEnd/src/Components/Carousel.jsx
> +/* eslint-disable react/prop-types */
Explained in the below comment

2023-05-15 14:10 UTC, leovaldez08 commented on FrontEnd/src/Components/Footer.jsx
> +/* eslint-disable react/prop-types */
Both of them are inbuilt rules of es-lint.
The first line is used to disable the rule which throws an error when a component uses an unknown HTML attribute.
The second line is used to disable the rule which throws an error when a component doesn't use the prop types correctly. In my case, it refused to accept the prop.
I chose to disable the rules as a temporary fix.

2023-05-15 14:19 UTC, leovaldez08 commented on FrontEnd/src/Components/Carousel.jsx
Understood! Added id to the CardData files and modified the map function!

2023-05-16 05:29 UTC, yash0212 requested changes
Please format all the changed files and resolve the comments

2023-05-16 05:29 UTC, yash0212 commented on FrontEnd/src/Components/HeroSection.jsx
> +            // maxW={{ base: "100%", md: "100%" }}
Commented code can be removed

2023-05-17 03:48 UTC, leovaldez08 commented on FrontEnd/src/Components/Footer.jsx
> +/* eslint-disable react/prop-types */
Resolved!

2023-05-17 06:26 UTC, leovaldez08 commented on FrontEnd/src/Components/HeroSection.jsx
> +            // maxW={{ base: "100%", md: "100%" }}
Done!

2023-05-17 06:28 UTC, merged